### ISSUE TITLE
Apple NVMe Assert failed

### ISSUE THREAD

**Issue by vorontsovdg** [ExtremeDot/MSI-X570-GAMING-PLUS-Hackintosh-Working-EFI-OpenCore#1]
Have you installed an OS with two m2 SSDs connected?
On my system with 2 sd m2: A data (Windows) and WD black (for Mac OS), when installing, I constantly get the error: AppleNVMe Assert Failed.
If only 1 ssd is connected: the OS is installed correctly

**Comment by ExtremeDot** [comment]
no i just installed on one ssd , others are on sata ports

**Comment by vorontsovdg** [comment]
thx!
The problem was wrong load order of Lilu.kext in my config.plist

**Comment by As262** [comment]
> thx!
> The problem was wrong load order of Lilu.kext in my config.plist

Can you tell me what you changed in config.plist im having same problem
